# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "./database-agent/src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
# with_docs=true

[migrations_directory]
dir = "./database-agent/migrations"
